"""
ql_sanity_check.py
==================
QuantLib sanity check for the OIS curve bootstrapper (crv_btstrpr.py).

Replicates the same OIS curve using QuantLib's PiecewiseLogLinearDiscount
bootstrapper with identical market inputs and conventions, then compares
the Exp_Fwd_SOFR_1D column (flat daily Act/360 rate over each tenor)
side by side to validate crv_btstrpr output.

Designed for SOFR-OIS but applicable to any overnight index curve
bootstrapped via crv_btstrpr.SOFRCurve.
"""
#%%
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import QuantLib as ql
from datetime import date

from crv_btstrpr import SOFRCurve, COLORS


# ── Helpers ───────────────────────────────────────────────────────────────────
def to_ql_date(d: date) -> ql.Date:
    return ql.Date(d.day, d.month, d.year)

def from_ql_date(d: ql.Date) -> date:
    return date(d.year(), d.month(), d.dayOfMonth())

def ql_act360_t(d1: ql.Date, d2: ql.Date) -> float:
    return ql.Actual360().yearFraction(d1, d2)

def compare_coupon_schedule(curve, tenor: str = "50Y") -> pd.DataFrame:
    """
    Compare the annual coupon schedule generated by crv_btstrpr (add_tenor
    iteration) vs QuantLib (Schedule with MF convention) for a given tenor.
    Helps diagnose date misalignments that cause long-end curve differences.
    """
    cal = ql.UnitedStates(ql.UnitedStates.GovernmentBond)
    dc  = ql.Actual360()
    bdc = ql.ModifiedFollowing

    mat     = curve.add_tenor(curve.effective_date, tenor)
    eff_ql  = to_ql_date(curve.effective_date)
    mat_ql  = to_ql_date(mat)

    # ── crv_btstrpr coupon dates ──────────────────────────────────────────────
    our_dates = curve._coupon_schedule(mat)

    # ── QuantLib coupon dates ─────────────────────────────────────────────────
    schedule = ql.Schedule(
        eff_ql, mat_ql,
        ql.Period(1, ql.Years),
        cal, bdc, bdc,
        ql.DateGeneration.Forward,
        False  # endOfMonth
    )
    ql_dates = [from_ql_date(d) for d in schedule][1:]  # skip effective date

    # ── Compare ───────────────────────────────────────────────────────────────
    n       = max(len(our_dates), len(ql_dates))
    our_pad = our_dates + [None] * (n - len(our_dates))
    ql_pad  = ql_dates  + [None] * (n - len(ql_dates))

    rows = []
    for i, (od, qd) in enumerate(zip(our_pad, ql_pad), 1):
        diff = (od - qd).days if od and qd else None
        rows.append((i, od, qd, diff))

    cmp = pd.DataFrame(rows, columns=["Coupon#", "crv_btstrpr", "QuantLib", "Diff_days"])

    mismatches = cmp[cmp["Diff_days"] != 0]
    print(f"\n{'='*70}")
    print(f"Coupon Schedule Comparison — {tenor} swap  |  Eff: {curve.effective_date}  Mat: {mat}")
    print(f"{'='*70}")
    print(f"Total coupons  : crv_btstrpr={len(our_dates)}  QuantLib={len(ql_dates)}")
    print(f"Mismatches     : {len(mismatches)}")
    if len(mismatches) > 0:
        print("\nMismatched coupons:")
        print(mismatches.to_string(index=False))
    else:
        print("All coupon dates match exactly ✅")

    return cmp


# ── Accrual fraction comparison ───────────────────────────────────────────────
def compare_accrual_fractions(curve, tenor: str = "50Y") -> pd.DataFrame:
    """
    Compare Act/360 accrual fractions coupon by coupon between
    crv_btstrpr and QuantLib for a given tenor swap.
    """
    dc  = ql.Actual360()
    mat = curve.add_tenor(curve.effective_date, tenor)

    fix_dates = curve._coupon_schedule(mat)

    rows     = []
    prev_our = curve.effective_date
    prev_ql  = to_ql_date(curve.effective_date)

    for fd in fix_dates:
        fd_ql     = to_ql_date(fd)
        alpha_our = curve.act360(prev_our, fd)
        alpha_ql  = dc.yearFraction(prev_ql, fd_ql)
        diff      = round((alpha_ql - alpha_our) * 360, 6)  # days equivalent
        rows.append((fd, round(alpha_our, 8), round(alpha_ql, 8), diff))
        prev_our  = fd
        prev_ql   = fd_ql

    cmp        = pd.DataFrame(rows, columns=["CouponDate", "alpha_crv", "alpha_QL", "Diff_days_equiv"])
    mismatches = cmp[cmp["Diff_days_equiv"] != 0.0]

    print(f"\n{'='*70}")
    print(f"Accrual Fraction Comparison — {tenor}  |  Eff: {curve.effective_date}")
    print(f"{'='*70}")
    print(f"Total coupons : {len(fix_dates)}")
    print(f"Mismatches    : {len(mismatches)}")
    if len(mismatches) > 0:
        print("\nMismatched fractions:")
        print(mismatches.to_string(index=False))
    else:
        print("All accrual fractions match exactly ✅")

    return cmp


def compare_pillar_dates(curve) -> pd.DataFrame:
    """
    Compare the maturity date QuantLib assigns to each OISRateHelper pillar
    vs the maturity date crv_btstrpr computes via add_tenor(effective_date, tenor).
    A mismatch here means the two bootstrappers anchor their pillars at
    different points on the time axis, causing DF differences that propagate
    through the entire long end.
    """
    cal = ql.UnitedStates(ql.UnitedStates.GovernmentBond)
    dc  = ql.Actual360()
    bdc = ql.ModifiedFollowing
    sofr_idx = ql.OvernightIndex("SOFR", 1, ql.USDCurrency(), cal, dc)

    ql.Settings.instance().evaluationDate = to_ql_date(curve.today)

    rows = []
    for _, row in curve.df_mkt[curve.df_mkt["Type"] == "Swap"].iterrows():
        sym   = row["Symbol"]
        mat   = row["MatDate"]        # crv_btstrpr maturity
        quote = float(row["Quote"]) / 100.0
        tenor_days = (mat - curve.effective_date).days

        # Build a single OISRateHelper and ask QuantLib for its pillar date
        helper = ql.OISRateHelper(
            2,
            ql.Period(tenor_days, ql.Days),
            ql.QuoteHandle(ql.SimpleQuote(quote)),
            sofr_idx
        )
        ql_mat = from_ql_date(helper.maturityDate())
        diff   = (ql_mat - mat).days
        rows.append((sym, row["Tenors"], mat, ql_mat, diff))

    cmp = pd.DataFrame(
        rows,
        columns=["Symbol", "Tenor", "Mat_crv_btstrpr", "Mat_QL", "Diff_days"]
    )
    mismatches = cmp[cmp["Diff_days"] != 0]

    print(f"\n{'='*70}")
    print("Pillar Date Comparison — OIS Swap Instruments")
    print(f"{'='*70}")
    print(f"\nMismatches: {len(mismatches)}")
    if len(mismatches) > 0:
        print("\nMismatched pillars:")
        print(mismatches.to_string(index=False))
    else:
        print("All pillar dates match exactly ✅")

    return cmp

# ── Main check function ───────────────────────────────────────────────────────
def ql_curve_check(curve: SOFRCurve) -> pd.DataFrame:
    """
    Build a QuantLib PiecewiseLogLinear OIS curve from the same inputs
    as the provided SOFRCurve instance, evaluate Exp_Fwd_SOFR_1D on the
    same tenor grid, and return a comparison DataFrame.
    """
    today_ql = to_ql_date(curve.today)
    ql.Settings.instance().evaluationDate = today_ql

    cal = ql.UnitedStates(ql.UnitedStates.GovernmentBond)
    dc  = ql.Actual360()
    bdc = ql.ModifiedFollowing
    eom = False

    # SOFR overnight index — Act/360, T+1 fixing lag
    sofr_idx = ql.OvernightIndex("SOFR", 1, ql.USDCurrency(), cal, dc)

    # ── Build rate helpers ────────────────────────────────────────────────────
    helpers = []

    for _, row in curve.df_mkt.sort_values("T").iterrows():
        sym   = row["Symbol"]
        typ   = row["Type"]
        quote = float(row["Quote"]) / 100.0
        mat   = row["MatDate"]

        if typ == "Rate":
            # Overnight deposit: DepositRateHelper T+1
            helpers.append(
                ql.DepositRateHelper(
                    ql.QuoteHandle(ql.SimpleQuote(quote)),
                    ql.Period(1, ql.Days),
                    1, cal, bdc, eom, dc
                )
            )

        elif typ == "Future":
            # CME 3M SOFR futures: FuturesRateHelper with exact IMM dates.
            # Exchange-defined dates — no settlement day rolling applies.
            # HW convexity adjustment passed explicitly.
            imm_start, imm_end = curve.imm_dates_from_symbol(sym)
            t1 = curve.act360(curve.today, imm_start)
            t2 = curve.act360(curve.today, imm_end)
            ca = curve.hw_ca(max(t1, 0.0), t2)
            # Quote from sheet is already IMM index price (e.g. 96.363)
            futures_price = float(row["Quote"])
            helpers.append(
                ql.FuturesRateHelper(
                    ql.QuoteHandle(ql.SimpleQuote(futures_price)),
                    to_ql_date(imm_start),
                    to_ql_date(imm_end),
                    dc,
                    ql.QuoteHandle(ql.SimpleQuote(ca)),
                )
            )

        elif typ == "Swap":
            sr = quote
            tenor_days = (mat - curve.effective_date).days
            # Use OISRateHelper for all tenors — more consistent with
            # crv_btstrpr which treats all swaps uniformly via the
            # par float leg identity regardless of tenor
            helpers.append(
                ql.OISRateHelper(
                    2,
                    ql.Period(tenor_days, ql.Days),
                    ql.QuoteHandle(ql.SimpleQuote(sr)),
                    sofr_idx
                )
            )

    # ── Bootstrap ─────────────────────────────────────────────────────────────
    ql_curve = ql.PiecewiseLogLinearDiscount(today_ql, helpers, dc)
    ql_curve.enableExtrapolation()

    # ── Evaluate on tenor grid ────────────────────────────────────────────────
    rows = []
    for _, grow in curve.grid.iterrows():
        tenor  = grow["Tenor"]
        mat    = grow["MatDate"]
        mat_ql = to_ql_date(mat)
        df_ql  = ql_curve.discount(mat_ql)
        ddays  = (mat - curve.today).days
        exp_fwd_ql = (
            ((1.0 / df_ql) ** (1.0 / ddays) - 1.0) * 360 * 100
            if ddays > 0 else np.nan
        )
        rows.append((tenor, mat, grow["Exp_Fwd_SOFR_1D"], exp_fwd_ql))

    cmp = pd.DataFrame(
        rows,
        columns=["Tenor", "MatDate", "Exp_Fwd_Arnulf", "Exp_Fwd_QL"]
    )
    cmp["Diff_bp"] = (cmp["Exp_Fwd_QL"] - cmp["Exp_Fwd_Arnulf"]) * 100

    print("\n" + "=" * 70)
    print("QuantLib Sanity Check — Exp_Fwd_SOFR_1D Comparison")
    print("=" * 70)
    print(cmp.to_string(index=False, float_format="%.6f"))
    print(f"\nMax abs diff : {cmp['Diff_bp'].abs().max():.4f} bp")
    print(f"Mean abs diff: {cmp['Diff_bp'].abs().mean():.4f} bp")

    # ── Plot ──────────────────────────────────────────────────────────────────
    cutoff = curve.add_tenor(curve.today, "3Y")
    cmp_short = cmp[cmp["MatDate"] <= cutoff].reset_index(drop=True)
    cmp_long = cmp[cmp["MatDate"] > cutoff].reset_index(drop=True)

    def _plot_panel(df: pd.DataFrame, label: str, save_name: str) -> None:
        tenors = df["Tenor"].tolist()
        grid_dates = df["MatDate"].tolist()

        fig, (ax0, ax1) = plt.subplots(2, 1, figsize=(14, 8), sharex=True)
        fig.suptitle(
            f"QuantLib vs crv_btstrpr — {label}  |  {curve.today}",
            fontsize=14, fontweight="bold"
        )

        ax0.plot(grid_dates, df["Exp_Fwd_Arnulf"],
                 "o-", color=COLORS[0], lw=2, label="crv_btstrpr")
        ax0.plot(grid_dates, df["Exp_Fwd_QL"],
                 "s--", color=COLORS[3], lw=1.5, label="QuantLib")
        ax0.set_ylabel("Rate (%)", fontsize=11)
        ax0.set_title("E[SOFR] Flat Daily Rate Act/360", fontsize=12)
        ax0.legend(fontsize=10)
        ax0.grid(True, alpha=0.2)

        ax1.fill_between(grid_dates, df["Diff_bp"], 0,
                         where=(df["Diff_bp"] >= 0),
                         color=COLORS[2], alpha=0.8, label="positive")
        ax1.fill_between(grid_dates, df["Diff_bp"], 0,
                         where=(df["Diff_bp"] < 0),
                         color=COLORS[2], alpha=0.8, label="negative")
        ax1.plot(grid_dates, df["Diff_bp"], color="black", lw=0.8)
        ax1.axhline(0, color="black", lw=0.8)
        ax1.set_ylabel("Diff (bp)", fontsize=11)
        ax1.set_title("QL − crv_btstrpr  (basis points)", fontsize=12)
        ax1.set_xticks(grid_dates)
        ax1.set_xticklabels(tenors, rotation=45, fontsize=9)
        ax1.set_ylim(-1,1)
        ax1.grid(True, alpha=0.2)

        plt.tight_layout()
        plt.savefig(save_name, dpi=150, bbox_inches="tight")
        plt.show()
        print(f"Chart saved → {save_name}")

    _plot_panel(cmp_short, "Short End (≤ 1Y)", "ql_sanity_short.png")
    _plot_panel(cmp_long, "Long End  (> 1Y)", "ql_sanity_long.png")
    _plot_panel(cmp, "", "ql_sanity.png")

    return cmp

#%% ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    sofr_file  = os.path.join(os.getcwd(), "marketinputs", "sofr.xlsx")
    today_date = pd.read_excel(
        sofr_file, sheet_name=0, header=0, usecols="F", nrows=1
    ).iloc[0, 0].date()
    curve = SOFRCurve(sofr_path=sofr_file, today=today_date)
    curve.bootstrap()
    curve.build_grid()
    cmp = ql_curve_check(curve)
    _ = compare_coupon_schedule(curve, "50Y")
    _ = compare_accrual_fractions(curve, "50Y")
    _ = compare_pillar_dates(curve)